import { Providers } from '@/app/providers'
import MatrixBackground from '@/components/matrix-background'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body suppressHydrationWarning>
        <MatrixBackground />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
